### PR TITLE
Fixes 13

### PR DESCRIPTION
**Pull request by baranyaib90**
Hi, briefly: some code modernization and a plan B for #161 
Br, Balázs

### CODE REVIEW

**Review by aarond10 — APPROVED** [review]

**Review by aarond10 — APPROVED** [review]

**Review by aarond10 — APPROVED** [review]
I really don't like the (void) stuff but if the linter likes it, sure. :)

**Review by aarond10 — APPROVED** [review]

**Comment by aarond10** [comment]
You're a champ! Thank you.

**Comment by baranyaib90** [comment]
You are welcome.

About the (void) stuff (Reference: https://clang.llvm.org/extra/clang-tidy/checks/cert/err33-c.html):

1. Ignoring it totally is a no go.
2. Having (void) right there shows - in a nasty syntax way - that return value is ignored on purpose. (As I recall, clang-tidy recommended the cast to void.)
3. Plan B would be to have //NOLINT(cert-err33-c) at the end of the line :S

**Comment by aarond10** [comment]
Yeah. Fair enough. I would prefer an opt-in (like ABSL_MUST_USE_RESULT) but
nevermind!

**Pull request merged**
