### PR TITLE
Update documentation to reference Docker install.

### PR DESCRIPTION
**Pull request by moranbw**
I created a pretty basic Dockerfile that pulls from your repo and builds.  I expose value-based flags as environment variables (i.e. DNS_SERVERS) and pure flags as cmd arguments (i.e. -4).

Perhaps running in a container is a fringe use case, but it seems to work well.

https://github.com/moranbw/https-dns-proxy-docker

### CODE REVIEW

**Comment by aarond10** [comment]
Nice. Thanks for putting the image together. I've been a bit busy so haven't checked it out myself yet. Comment LGTM.

**Comment by moranbw** [comment]
Great! Lemme know if you have any feedback :)

**Comment by moranbw** [comment]
@aarond10 just realized I put the wrong link for Docker Image. I embedded link for my management view. Not public view. It should be this https://hub.docker.com/r/bwmoran/https-dns-proxy. 

I can make another PR, whatever is easier for you.

**Comment by aarond10** [comment]
A pull request would be great if you have the time, otherwise I'll have to
look at it in a day or two.

**Pull request merged**
