### PR TITLE
Fixes and improvements 3

### PR DESCRIPTION
**Pull request by baranyaib90**
Hi,
As before, here are again my changes, that I would like to share:

1. fixing issue: #105
2. some house cleaning: typos, whitespaces, dead code and install manual update
3. graceful shutdown feature
4. in HTTP client: enhanced error handling of responses to help users

That's all, I hope, you will like it.
Sincerely,
Balázs

### CODE REVIEW

**Review by aarond10 — APPROVED** [review]

**Review by aarond10 — APPROVED** [review]

**Review by aarond10 — APPROVED** [review]

**Review by aarond10 — APPROVED** [review]

**Review by aarond10 — APPROVED** [review]

**Review by aarond10 — APPROVED** [review]
I like this but I'm curious about where it came from. Did you see this happen?

**Review by aarond10 — APPROVED** [review]

**Review by aarond10 — APPROVED** [review]

**Comment by baranyaib90** [comment]
> I like this but I'm curious about where it came from. Did you see this happen?

Sorry, but I don't get the context.
Could you please link the commit and/or the changed file name and line number please?
Thanks!

**Comment by Soldy** [comment]
:)  [#105](https://github.com/aarond10/https_dns_proxy/issues/105)

**Comment by aarond10** [comment]
Oh, I was referring to the redirection handling. Did you find that
happening in practice?

**Comment by baranyaib90** [comment]
> Oh, I was referring to the redirection handling. Did you find that happening in practice?

Actually: no.
I just wanted to disable redirections for good, to ensure performance.
And since I did not allow it, I have updated logging to warn user if it would happen.

Off topic: there's an other small response handling bug:
If you set https://dns.google/ as resolver, and send any DNS query, the HTML page will be sent back in the DNS reply packet :D
According to: [RFC 8484 Section 4.2](https://tools.ietf.org/html/rfc8484#section-4.2)
I will add a check, to verify, that the response [Content-Type](https://curl.se/libcurl/c/CURLINFO_CONTENT_TYPE.html) is "application/dns-message" or not.

**Pull request merged**
